package mvt

import (
	"strings"
	"testing"
)

// The fixtures below are the message examples from OAG's freely published
// "MVT / MVA / DIV Aircraft Movement Messages: Data Elements and Message
// Examples", copied by hand, character for character. They are external
// artefacts on purpose: a fixture generated by this package's own builder
// would prove nothing, which is the trap this repository has fallen into
// twice before.

func TestParseDepartureExample(t *testing.T) {
	// Departure message, four-digit time form, from the OAG examples.
	m, err := Parse("MVT\nSD200/21.PMDFG.CDG\nAD1100/1115 EA1500 FRA\nDL72/0015\nPX112\nSI DEICING")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.Kind != KindMVT || m.Flight != "SD200" || m.Day != "21" ||
		m.Registration != "PMDFG" || m.Station != "CDG" {
		t.Fatalf("identification read wrong: %+v", m)
	}
	if m.AD == nil || m.AD.First != "1100" || m.AD.Second != "1115" {
		t.Errorf("AD = %+v, want 1100/1115", m.AD)
	}
	if m.EA == nil || m.EA.Time != "1500" || m.EA.Airport != "FRA" {
		t.Errorf("EA = %+v, want 1500 FRA", m.EA)
	}
	if len(m.Delays) != 1 || m.Delays[0] != (Delay{Code: "72", Duration: "0015"}) {
		t.Errorf("Delays = %+v, want [72/0015]", m.Delays)
	}
	if len(m.Pax) != 1 || m.Pax[0] != 112 {
		t.Errorf("Pax = %v, want [112]", m.Pax)
	}
	if m.SI != "DEICING" {
		t.Errorf("SI = %q, want DEICING", m.SI)
	}
	if len(m.Unrecognised) != 0 {
		t.Errorf("nothing in this example should be unrecognised: %v", m.Unrecognised)
	}
}

func TestParseDepartureSixDigitForm(t *testing.T) {
	// The same departure in the six-digit UTC date-and-time form.
	m, err := Parse("MVT\nSD200/21.PMDFG.CDG\nAD211100/211115 EA1500 FRA\nDL72/0015\nPX112\nSI DEICING")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.AD == nil || m.AD.DayA != "21" || m.AD.First != "1100" ||
		m.AD.DayB != "21" || m.AD.Second != "1115" {
		t.Errorf("AD = %+v, want 21+1100 / 21+1115", m.AD)
	}
}

func TestParseArrivalExample(t *testing.T) {
	m, err := Parse("MVT\nSD200/22.PMDFG.FRA\nAA1515/1520\nFLD22")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.Station != "FRA" {
		t.Errorf("an arrival message carries the arrival airport; got %q", m.Station)
	}
	if m.AA == nil || m.AA.First != "1515" || m.AA.Second != "1520" {
		t.Errorf("AA = %+v, want 1515/1520", m.AA)
	}
	if m.FLD != "22" {
		t.Errorf("FLD = %q, want 22", m.FLD)
	}
}

func TestParseDelayExample(t *testing.T) {
	m, err := Parse("MVT\nSD200/22.PMDFG.CDG\nED221125\nDL72/0025")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.ED != "221125" {
		t.Errorf("ED = %q, want 221125", m.ED)
	}
}

func TestParseIndefiniteDelayUsesNextInfo(t *testing.T) {
	m, err := Parse("MVT\nSD200/22.PMDFG.CDG\nNI221150\nSI ENGINE TROUBLE")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.NI != "221150" {
		t.Errorf("NI = %q, want 221150", m.NI)
	}
	if m.SI != "ENGINE TROUBLE" {
		t.Errorf("SI = %q", m.SI)
	}
}

func TestParseDelayedTakeOffExample(t *testing.T) {
	m, err := Parse("MVT\nSD200/22.PMDFG.CDG\nAD221115 EO1135 EA1530 FRA\nDL72/0025\nEB1545")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.AD == nil || m.AD.DayA != "22" || m.AD.First != "1115" || m.AD.Second != "" {
		t.Errorf("AD = %+v, want 22+1115 with no airborne time", m.AD)
	}
	if m.EO != "1135" || m.EB != "1545" {
		t.Errorf("EO/EB = %q/%q, want 1135/1545", m.EO, m.EB)
	}
	if m.EA == nil || m.EA.Time != "1530" || m.EA.Airport != "FRA" {
		t.Errorf("EA = %+v", m.EA)
	}
}

func TestParseReturnToRampExample(t *testing.T) {
	m, err := Parse("MVT\nSD200/22.PMDFG.CDG\nAD1115 RR1125\nDL72/0015\nSI ABORTED TAKE-OFF")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.RR != "1125" {
		t.Errorf("RR = %q, want 1125", m.RR)
	}
	if m.SI != "ABORTED TAKE-OFF" {
		t.Errorf("SI = %q", m.SI)
	}
}

func TestParseReturnFromAirborneExample(t *testing.T) {
	m, err := Parse("MVT\nSD200/22.PMDFG.CDG\nFR1200/1215\nSI ENGINE 1 TROUBLE")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.FR == nil || m.FR.First != "1200" || m.FR.Second != "1215" {
		t.Errorf("FR = %+v, want 1200/1215", m.FR)
	}
}

func TestParseRevisedETAExample(t *testing.T) {
	// Sent at the arrival station, so EA carries no airport.
	m, err := Parse("MVT\nSD200/22.PMDFG.FRA\nEA1515\nEB1525\nSI RADAR FAILURE")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.EA == nil || m.EA.Time != "1515" || m.EA.Airport != "" {
		t.Errorf("EA = %+v, want bare 1515", m.EA)
	}
}

func TestParseDiversionExample(t *testing.T) {
	m, err := Parse("DIV\nSD200/30.CVBNM.MAN\nEA1125 STN\nDR71 PX112\nSI BAD WEATHER")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if m.Kind != KindDIV {
		t.Fatalf("Kind = %q, want DIV", m.Kind)
	}
	if m.Station != "MAN" {
		t.Errorf("a DIV carries the originally intended airport; got %q", m.Station)
	}
	if m.EA == nil || m.EA.Time != "1125" || m.EA.Airport != "STN" {
		t.Errorf("EA = %+v, want 1125 STN (the diversion airport)", m.EA)
	}
	if m.DR != "71" {
		t.Errorf("DR = %q, want 71", m.DR)
	}
	if len(m.Pax) != 1 || m.Pax[0] != 112 {
		t.Errorf("Pax = %v, want [112]", m.Pax)
	}
}

func TestParseTwoDelaysAndSubCodes(t *testing.T) {
	m, err := Parse("MVT\nSD200/21.PMDFG.CDG\nAD1100/1115 EA1500 FRA\nDL64/72/0015/0020\nDLA841/812/932/652")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	want := []Delay{{Code: "64", Duration: "0015"}, {Code: "72", Duration: "0020"}}
	if len(m.Delays) != 2 || m.Delays[0] != want[0] || m.Delays[1] != want[1] {
		t.Errorf("Delays = %+v, want %+v: codes come first, then durations, matched by position", m.Delays, want)
	}
	if len(m.SubCodes) != 4 || m.SubCodes[0] != "841" {
		t.Errorf("SubCodes = %v", m.SubCodes)
	}
}

func TestParsePaxPerDestination(t *testing.T) {
	m, err := Parse("MVT\nSD200/21.PMDFG.CDG\nAD1100/1115\nPX12/134/10")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(m.Pax) != 3 || m.Pax[0] != 12 || m.Pax[1] != 134 || m.Pax[2] != 10 {
		t.Errorf("Pax = %v, want [12 134 10]", m.Pax)
	}
}

func TestParseCorrection(t *testing.T) {
	m, err := Parse("COR MVT\nSD200/21.PMDFG.CDG\nAD1102/1117")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if !m.Correction {
		t.Error("a COR prefix marks the message as a correction")
	}
}

func TestUnrecognisedLinesAreKept(t *testing.T) {
	m, err := Parse("MVT\nSD200/21.PMDFG.CDG\nAD1100/1115\nTOF6400\nZFW132500")
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(m.Unrecognised) != 2 || m.Unrecognised[0] != "TOF6400" {
		t.Errorf("fuel and weight elements this grammar does not model must be kept verbatim; got %v",
			m.Unrecognised)
	}
}

func TestIsMovement(t *testing.T) {
	for text, want := range map[string]bool{
		"MVT\nSD200/21.PMDFG.CDG":     true,
		"MVA\nSD200/21.PMDFG.CDG":     true,
		"DIV\nSD200/30.CVBNM.MAN":     true,
		"COR MVT\nSD200/21.PMDFG.CDG": true,
		"AVS\nBA0175/29SEP LHRJFK":    false,
		"SS\nBA0117Y16DECLHRJFKNN1":   false,
	} {
		if got := IsMovement(text); got != want {
			t.Errorf("IsMovement(%q) = %v, want %v", text, got, want)
		}
	}
}

// FuzzRoundTrip holds the builder and parser to each other, which is the
// property every codec in this repository is held to: anything Build writes,
// Parse must read back to the same message. Both the AVS and Type B codecs
// shipped defects of exactly this shape before their fuzz targets existed.
func FuzzRoundTrip(f *testing.F) {
	f.Add("SD200", "21", "PMDFG", "CDG", "1100", "1115", "1500", "FRA", "72", "0015", 112, "DEICING")
	f.Add("BA117", "05", "GXWBA", "LHR", "0902", "0917", "1205", "JFK", "93", "0140", 214, "")
	f.Add("AF1680", "28", "FGKXL", "CDG", "", "", "", "", "", "", 0, "")

	f.Fuzz(func(t *testing.T, flight, day, reg, station, adA, adB, eaT, eaApt, dlCode, dlDur string, pax int, si string) {
		m := &Message{Kind: KindMVT, Flight: flight, Day: day, Registration: reg, Station: station}
		if plausibleTime(adA) {
			m.AD = &TimePair{First: adA}
			if plausibleTime(adB) {
				m.AD.Second = adB
			}
		}
		if plausibleTime(eaT) && len(eaApt) == 3 && allUpper(eaApt) {
			m.EA = &ETA{Time: eaT, Airport: eaApt}
		}
		if len(dlCode) == 2 && allDigits(dlCode) && len(dlDur) == 4 && allDigits(dlDur) {
			m.Delays = []Delay{{Code: dlCode, Duration: dlDur}}
		}
		if pax > 0 && pax < 1000 {
			m.Pax = []int{pax}
		}
		if si != "" && !strings.ContainsAny(si, "\n\r") && strings.TrimSpace(si) == si &&
			si == strings.ToUpper(si) && !strings.Contains(si, "  ") {
			m.SI = si
		}

		text, err := m.Build()
		if err != nil {
			t.Skip() // an identification the wire form refuses is not a round-trip case
		}
		got, err := Parse(text)
		if err != nil {
			t.Fatalf("Build produced text Parse rejects: %v\n%s", err, text)
		}
		if len(got.Unrecognised) != 0 {
			t.Fatalf("Build produced lines Parse could not read back: %v\n%s", got.Unrecognised, text)
		}
		if got.Flight != m.Flight || got.Day != m.Day || got.Station != m.Station {
			t.Fatalf("identification changed across the round trip: %+v -> %+v", m, got)
		}
		if (m.AD == nil) != (got.AD == nil) || (m.AD != nil && *got.AD != *m.AD) {
			t.Fatalf("AD changed: %+v -> %+v\n%s", m.AD, got.AD, text)
		}
		if (m.EA == nil) != (got.EA == nil) || (m.EA != nil && *got.EA != *m.EA) {
			t.Fatalf("EA changed: %+v -> %+v\n%s", m.EA, got.EA, text)
		}
		if len(got.Delays) != len(m.Delays) {
			t.Fatalf("delays changed: %+v -> %+v", m.Delays, got.Delays)
		}
		if got.SI != m.SI {
			t.Fatalf("SI changed: %q -> %q", m.SI, got.SI)
		}
	})
}

func plausibleTime(s string) bool {
	if len(s) != 4 || !allDigits(s) {
		return false
	}
	return s[0] <= '2' && !(s[0] == '2' && s[1] > '3') && s[2] <= '5'
}
